name: Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  BUILD_TYPE: Debug

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@b9f8889ab27f3d0f2ccb6d24fba79ea64638f253

      - name: Conan Install and Build
        env:
          CC: ${{ matrix.compiler.cc }}
          CXX: ${{ matrix.compiler.cxx }}
          SINGLE_HEADER: ${{ matrix.compiler.single_header }}
          CXX_STANDARD: ${{ matrix.compiler.cxx_standard }}
        run: mkdir ${{github.workspace}}/build && cd ${{github.workspace}}/build && conan install .. --build=missing -pr:b=default && conan build ..

      - name: Create Package
        run: cd ${{github.workspace}}/build && conan create ..

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target release_header

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: ${{github.workspace}}/build/include/cib/cib.hpp
          generate_release_notes: true
          draft: true


